name: Android Build

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test



      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
